### ISSUE TITLE
PowerPC packages

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/cudnn-feedstock#18]
They are missing right now. When available, the `conda_build_config.yaml` file in `nvcc-feedstock` will need to be updated.

_Originally posted by @kkraus14 in https://github.com/conda-forge/nvcc-feedstock/pull/66#discussion_r616859281_

**Comment by leofang** [comment]
I have a question for @jakirkham @kkraus14: Why do we have to zip cudnn with nvcc versions? We don't do this for other CUDA libraries (nccl, cutensor, ...). It seems inconvenient and error-prone to me to treat cudnn differently.

**Comment by jakirkham** [comment]
IIUC that was added in PR ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1051 )

cc @isuruf (in case you have thoughts here)

**Comment by kkraus14** [comment]
IIRC it's because certain CUDA versions only support cuDNN 7 whereas other CUDA versions only support cuDNN 8

**Comment by leofang** [comment]
> IIRC it's because certain CUDA versions only support cuDNN 7 whereas other CUDA versions only support cuDNN 8

I think for this case the pinning is better done via `run_exports` in the recipe.

**Comment by leofang** [comment]
On the ppc64le support: The last release that contained a downloadable archive for ppc64le + CUDA 10.2 is 8.0.5. After that, all ppc64le packages are released only for CUDA 11.0+, which we do not support here yet. Should we create a new breach to package 8.0.5 for ppc64le?

**Comment by jakirkham** [comment]
Sure that seems reasonable

**Comment by leofang** [comment]
OK thanks @jakirkham. Could you create a new branch for me against which I can send a PR? I am not yet a maintainer here.

**Comment by leofang** [comment]
Manually done in #25.
