### ISSUE TITLE
Feedstock maintenance

### ISSUE THREAD

**Issue by IvanYashchuk** [conda-forge/cudnn-feedstock#22]
Currently, the list of maintainers of this recipe includes only Keith, who is taking a time off. And @leofang expressed his interest to become a maintainer in https://github.com/conda-forge/cudnn-feedstock/pull/21.

@jakirkham, @raydouglass as you're maintainers of the CUDA Toolkit and NCCL feedstocks would you be interested in maintaining cuDNN as well?

**Comment by leofang** [comment]
@IvanYashchuk Would you be interested? 😁

**Comment by leofang** [comment]
Closing as Ivan is on board 😁
