### ISSUE TITLE
Any legal issue for repackaging and redistribution?

### ISSUE THREAD

**Issue by farleylai** [conda-forge/cudnn-feedstock#30]
I am planning to make a recipe for  TensorRT just like the CuDNN package in `conda-forge`. Despite the license agreement declaration at the time of installation through conda, is it truly legal issue free to repackage and redistribute nvidia packages that require login to download through the public anaconda repo?

**Comment by leofang** [comment]
@conda-forge/core can answer this question more accurately, but I think the general legal issue has been addressed before all these CUDA components were pushed to conda-forge by NVIDIA folks. As long as your users are installing from conda-forge it should be fine.

**Comment by isuruf** [comment]
It's fine for conda-forge to redistribute, but you are not allowed to redistribute it yourself.

**Comment by farleylai** [comment]
> It's fine for conda-forge to redistribute, but you are not allowed to redistribute it yourself.

Redistribution through conda-forge is totally OK.
It is just not clear what is the formal process to redistribute other packages not available through conda-forge yet such as TensorRT. 

Could you elaborate what makes it carefree for redistribution through conda-forge?
Is it a separate agreement signed between conda-forge and nvidia on a per package basis?
If that is the case, what does this authorization process looks like?
Is it initiated on the nvidia side or did conda-forge make a formal request once before?

**Comment by leofang** [comment]
@farleylai For any general discussion I would refer you to reach out to the conda-forge core team via Gitter (https://gitter.im/conda-forge/conda-forge.github.io). I am closing this issue as it is no longer specific to this feedstock. Thanks!
