### ISSUE TITLE
why was support for 10.x dropped?

### ISSUE THREAD

**Issue by ngam** [conda-forge/cudnn-feedstock#47]
### Comment:

unclear to me how this makes sense --- are we supposed to drop support for downstream packages as well? Most popular packages that actually use cudnn are x86_64 anyway, so I am not sure how this reasoning came to be. Could the maintainers elaborate?

https://github.com/conda-forge/cudnn-feedstock/blob/2ab019f80eb7bc023e7fa4bdea98777373185edc/recipe/meta.yaml#L3-L8

```yaml

# cuDNN v8.3.x supports CUDA versions 10.2 - 11.5
# For CUDA 11.x there is one cuDNN distribution that works with all CUDA 11 versions
# (We don't support CUDA 10.2 anymore as it's x86-64 only.)
{% if cuda_compiler_version[:2] == "11" %}
{% set cudnn_cuda_version = "11.5" %}
{% endif %}

```

xref: https://github.com/conda-forge/cudnn-feedstock/pull/46
xref: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/284

**Comment by ngam** [comment]
There is clearly a cudnn 8.4.1.x for 10.x, here' the link: https://developer.download.nvidia.com/compute/redist/cudnn/v8.4.1/local_installers/10.2/

**Comment by ngam** [comment]
(Note: I am personally 100% strongly in support of completely dropping everything below cuda 11.2 --- I just want us to do this logically and consistently in the conda-forge ecosystem and I don't want us to have ad-hoc policies and/or implementations since that's pretty bad)

**Comment by ngam** [comment]
> conda-forge has moved on and dropped 10.2 support, I think there're some threads/PRs in the global pinning feedstock. Now the remaining CUDA 10.2 support you see in individual feedstocks are mostly just leftover and done before the drop of 10.2.

Could you please link to these discussions? I am not really sure that is the case. At least in the tensorflow and pytorch feedstock, we wish we could just drop 10.x, but we don't because we want to keep the ecosystem intact and support as many users possible. We also want to follow upstreams implementations.

**Comment by isuruf** [comment]
Hasn't happened yet. See https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1708

**Comment by leofang** [comment]
OK thanks for clarifying Isuru. I suppose if CUDA 10.2 users/feedstock maintainers need the new version they are welcome to help maintain CUDA 10.2 support, but let me note that `cudnn` 8.x + `cudatoolkit` 10.2 is already solvable so technically it's not a blocker:
```
$ conda create -n ppppp cudatoolkit=10.2 cudnn=8
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.3
  latest version: 4.13.0

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /home/leof/miniforge3/envs/ppppp

  added / updated specs:
    - cudatoolkit=10.2
    - cudnn=8


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cudatoolkit-10.2.89        |      h713d32c_10       449.7 MB  conda-forge
    cudnn-8.2.1.32             |       h2c0ae14_0       361.5 MB  conda-forge
    ------------------------------------------------------------
                                           Total:       811.2 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-2_gnu
  cudatoolkit        conda-forge/linux-64::cudatoolkit-10.2.89-h713d32c_10
  cudnn              conda-forge/linux-64::cudnn-8.2.1.32-h2c0ae14_0
  libgcc-ng          conda-forge/linux-64::libgcc-ng-12.1.0-h8d9b700_16
  libgomp            conda-forge/linux-64::libgomp-12.1.0-h8d9b700_16
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-12.1.0-ha89aaad_16


Proceed ([y]/n)? 
```

**Comment by ngam** [comment]
> I suppose if CUDA 10.2 users/feedstock maintainers need the new version they are welcome to help maintain CUDA 10.2 support

I cannot take you seriously anymore. 

You blocked cudnn 8.3.x for more than six months because [you wanted to make Windows users happy](https://github.com/conda-forge/cudnn-feedstock/pull/38#issuecomment-1149026773) but now you say, users are welcome to contribute this! You are not explaining the decision --- was it just a mistake on your part thinking that the ecosystem has moved on? Or was it agreed upon in the private channels/communication that you people have?

Since [you were the one who contributed the commit](14f3b2db89c728ecf65641b94f6918258659b946) in question, would you be willing to reinstate 10.2 support in cudnn 8.4.1.50 when that PR comes or in cudnn 8.4.0.27 in PR #45? 

Also, I thought [you wanted out of this feedstock](https://github.com/conda-forge/cudnn-feedstock/pull/38/commits/60bfb71315252e645c3ab2d479f7896250d810cf) or are you reconsidering that? Since you're still pretty heavily involved in driving decisions it seems...

**Comment by ngam** [comment]
I know I sound adversarial here: I really want us to hold each other accountable. I want us to have all the nvidia packages in good standing and in logical and consistent manner. We spend a lot of time working on packages that benefit from cudnn (e.g. tensorflow and pytorch) and they do make a difference in the quality of packages we publish on conda-forge (e.g. our conda-forge's tensorflow>=2.8.1 has the highest performance that I am aware of).

**Comment by leofang** [comment]
Let me be clear. 
> You blocked cudnn 8.3.x for more than six months 

I didn't block it, it's blocked by having to get https://github.com/conda-forge/zlib-feedstock/pull/54 merged first, which admittedly was involved and people were short on bandwidth, but it's not my decision alone. I cannot accept you making up the fact.

> would you be willing to reinstate 10.2 support

Following the [same hostile manner](https://github.com/conda-forge/cudnn-feedstock/pull/43#discussion_r899227804) that you did, I kindly refuse your request. We have enough unpleasant interaction for the day, and as volunteer effort I don't owe you anything. You could have asked nicely.

**Comment by ngam** [comment]
> I cannot accept you making up the fact.

Not making up anything, you have indeed blocked cudnn without windows: https://github.com/conda-forge/cudnn-feedstock/pull/41#pullrequestreview-988209413



> You could have asked nicely

Lol what? I am not asking you, I could do this and frankly could do a better job than you :)  I am just saying, you should have acted better before recklessly dropping 10.2 without further consultation. 

> Following the [same hostile manner](https://github.com/conda-forge/cudnn-feedstock/pull/43#discussion_r899227804) that you did

For the record, my actions in #43 weren't hostile at all. I just thought your request was nonsensical (and irrelevant) and so I didn't want do it; a maintainer with push access could have if they wanted to (and have in fact actually done so in [01e55c8](https://github.com/conda-forge/cudnn-feedstock/pull/43/commits/01e55c8ae982356b2ae8843f481b8d0da7397be2))

**Comment by ngam** [comment]
I will work with the new maintainer(s) to reinstate 10.2 support. Thanks for all your hard work!

**Comment by ngam** [comment]
I will close this now so to avoid unnecessary traffic and conversation. I will bring this up in a PR after all current PRs are done, unless there are new developments in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1708

**Comment by ngam** [comment]
@leofang, I deleted some comments that may come across hostile again, so please don't take this and stuff in PR #43 personally. I really appreciate all your work and efforts and insights. You're very generous and kind with your time, and I genuinely mean this. I promise a PR to reinstate 10.2 that will be less hostile and maybe that way you can help me with it? 🕊️❤️ (It won't include the azure artifacts 😉)
