### ISSUE TITLE
Need Cudnn 8.7 for TensorFlow

### ISSUE THREAD

**Issue by haifeng-jin** [conda-forge/cudnn-feedstock#52]
### Comment:

Dear developers,

I am Haifeng from the TensorFlow team.
Thank you for working on this wonderful package!

As you can see [here](https://www.tensorflow.org/install/pip), we are relying on this cudnn from conda-forge for our users to install TensorFlow.

However, for the next release (TensorFlow 2.12), we upgraded to use **cudnn 8.7**.
I wonder if it is possible to add this new version cudnn to conda-forge.

Thank you!
@ivanyashchuk
@kkraus14

**Comment by IvanYashchuk** [comment]
Hello Haifeng,
I'm not maintaining this package anymore, Keith is also not around.
Maybe the TensorFlow team would be willing to begin maintaining this package?

**Comment by jakirkham** [comment]
We are in the process of restructuring the CUDA packages in conda-forge in tandem with adding CUDA 12 ( https://github.com/conda-forge/staged-recipes/issues/21382 ). Think we should discuss this as part of that effort
