### ISSUE TITLE
cuDNN: Support CUDA 12

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cudnn-feedstock#54]
Depends on issue ( https://github.com/conda-forge/staged-recipes/issues/21382 )

**Comment by leofang** [comment]
NVIDIA has not released a cuDNN version that supports CUDA 12 yet.

**Comment by jakirkham** [comment]
Or perhaps more generally figuring out how we handle this package as part of those changes

**Comment by FRidh** [comment]
There is [now a CUDA 12 cuDNN](https://developer.download.nvidia.com/compute/redist/cudnn/v8.8.0/local_installers/12.0/), however, they no longer upload archives. This is an issue for us at Nixpkgs. Does anyone here (including maintainer @kkraus14) have a way to contact NVIDIA to release the archives?

**Comment by FRidh** [comment]
I was just told the archives were moved to https://developer.download.nvidia.com/compute/cudnn/redist/cudnn/linux-x86_64/.

**Comment by jakirkham** [comment]
Looks like `8.8.0.121` is the first version supporting CUDA 12

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render

**Comment by jakirkham** [comment]
Added PR ( https://github.com/conda-forge/cudnn-feedstock/pull/59 ) to apply the CUDA 12 migration on this feedstock. Not expecting many changes from that
