### ISSUE TITLE
Add CUDA 12 + Windows package

### ISSUE THREAD

**Issue by leofang** [conda-forge/cudnn-feedstock#63]

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by leofang** [comment]
There's also a CI config file for CUDA 12 + Windows:
https://github.com/conda-forge/cudnn-feedstock/blob/main/.ci_support/win_64_cuda_compilercuda-nvcccuda_compiler_version12.0.yaml

**Comment by jakirkham** [comment]
Yeah the re-render didn't do anything either: https://github.com/conda-forge/cudnn-feedstock/pull/68#issuecomment-1834384694

So maybe that `skip` didn't work

**Comment by jakirkham** [comment]
Yeah the package definitely built and uploaded [on CI]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=825399&view=logs&j=171a126d-c574-5c8c-1269-ff3b989e923d&t=623c2ba8-c4f1-582d-6c78-1c7699e2e0a2&l=594 )

In any event will go ahead and drop the `skip` just to be safe
