### ISSUE TITLE
Need cuDNN v8.x for CUDA 11

### ISSUE THREAD

**Issue by leofang** [conda-forge/cudnn-feedstock#8]
See https://github.com/conda-forge/cupy-feedstock/issues/81. This is a blocker for any CUDA 11 migrations if the feedstock depends on `cudnn`.

**Comment by isuruf** [comment]
PRs are welcome.

**Comment by isuruf** [comment]
Done

**Comment by leofang** [comment]
Wow thanks a lot @isuruf! I suppose the bot will resume scheduling of CUDA 11.0 migrations blocked by this?

**Comment by isuruf** [comment]
No, the migration is blocked by https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1051

**Comment by leofang** [comment]
I see, thanks.
