### ISSUE TITLE
libzlib doesn't follow the global pin

### ISSUE THREAD

**Issue by njzjz** [conda-forge/cudnn-feedstock#81]
### Comment:

It looks like the latest cudnn requires the latest libzlib (v1.3), but not the zlib version in the global pin (v1.2).

See: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=894756&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=6d4b912b-175d-51da-0fd9-4d30fe1eb4e7&l=881
![image](https://github.com/conda-forge/cudnn-feedstock/assets/9496702/c52d41a9-04f5-46ec-9ac4-1d7d0ef94483)

This became a problem after zlib 1.3 was released two months ago.

I found this issue in https://github.com/conda-forge/pytorch-cpu-feedstock/pull/224#issuecomment-1993358085.

**Comment by jakirkham** [comment]
Thanks Jinzhe! 🙏

Was looking at the same thing. Should be fixed with PR: https://github.com/conda-forge/cudnn-feedstock/pull/82
